import pandas as pd
 
df = pd.read_csv("students_data.csv")
 
print("1. head():\n", df.head())
print()
print("2. tail():\n", df.tail(3))
print()
print("3. info():")
df.info()
print()
print("4. describe():\n", df.describe())
print()
print("5. shape:", df.shape)
print()
print("6. columns:", df.columns.tolist())
print()
print("7. sort_values('Marks'):\n", df.sort_values("Marks", ascending=False))
print()
print("8. groupby('Department').mean(numeric_only=True):\n", df.groupby("Department").mean(numeric_only=True))
print()
print("9. filter Marks > 75:\n", df[df["Marks"] > 75])
print()
print("10. value_counts('City'):\n", df["City"].value_counts())