# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuWJeELTGX9Wg1nke9jNhpF6_5xPbCJv

**List**
"""

list_1 = [22,34,56,51,20,80,99]
a = list_1
print(a)
print(a[1])
print(a[2:6])
print(a[1:6:2])
print(a[:-2])

"""**List Function**"""

list_1 = [22,34,56,51,20,80,99]
a = list_1
a.append(39)
print(a)
a.remove(99)
print(a)
a.pop()
print(a)
a.extend(["lokesh", 1])
print(a)
a.insert(2,"11")
print(a)

"""**Tuple**"""

tup = (22,32,45,76,87)
print(type(tup))
print(tup[2])
print(tup[1:4])
print(tup[1:4:2])

"""**Tuples Methods**"""

tup_1 = (1,2,3,1,1,2)
print(tup_1)
print(tup_1.index(2))
print(tup_1.count(1))

"""**Dictionary**"""

dict = {
    "name" : "lokesh",
    "age" : 19,
    "city" : "surat"
}
print(type(dict))
print(dict)
dict["name"] = "rahul"
print(dict)
dict["surname"] = "patil"
print(dict)

"""**Dictionary Methods**"""

dict_1 = {
    "name" : "rahul",
    "age" : 20,
    "city" : "surat"
}
print(dict_1)
print(dict_1.keys())
print(dict_1.values())
print(dict_1.items())
print(dict_1.get("age"))
dict_1.update({"marks" : 99})
print(dict_1)

"""**Set**"""

set = {1,2,3,1,2,4,2}
print(set)
print(len(set))

"""**Set Methods**"""

set_1 = {22,32,11,23}
print(set_1)
set_1.add(20)
print(set_1)
set_1.remove(11)
print(set_1)
set_1.pop()
print(set_1)

"""**Conditional Statements**

**if**
"""

a = 100
b = 20
if a>b :
  print("a is greater")

"""**if-else**"""

a = 10
b = 20
if a>b :
  print("a is greater")
else:
    print("b is greater")

"""**if-elif-else**"""

marks = 80
if marks>90 :
  print("A grade")
elif marks>80 :
    print("B grade")
elif marks>70 :
      print("C grade")
else :
        print("D grade")

"""**Nested if-else**"""

mun = 15
if mun > 0 :
  if mun %2 == 0 :
    print("even number")
  else :
    print("odd number")
else :
  print("number is negative")

"""**Input Method**"""

name = input("enter your name:")
print("your name is :", name)

"""**range Functions**"""

for i in range(1,10) :
  print(i)

for i in range (2,20,2) :
  print(i)

"""**len(), type() Functions**"""

list_1 = [22,34,11,20,30,50]
print(len(list_1))
print(type(list_1))


"""**Break, continue, pass**"""

names = ["Alice", "Bob", "Charlie"]
for i in range(len(names)):
    print(names[i])
    print(type(names[i]))
    if names[i] == "Bob":
        break

for num in range(5):
    if num % 2 == 0:
        print(num)
    else:
        continue

for val in range(3):
    if val == 0:
        print("Zero")
    elif val == 1:
        print("One")
    else:
        print("Other")



"""**For, while loops**"""

for val in range(3):
    if val == 0:
        print("Zero")
    elif val == 1:
        print("One")
    else:
        print("Other")





        
user_input = input("Enter a number (or 'exit' to quit): ")
while user_input != "exit":
    if user_input.isdigit():
        num = int(user_input)
        if num > 0:
            if num % 2 == 0:
                print("Positive Even")
            else:
                print("Positive Odd")
        else:
            print("Non-positive")
    else:
        pass
    user_input = input("Enter a number (or 'exit' to quit): ")






